// ------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本: 17.0.0.0
//  
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，則會遺失變更。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SitecoreService.MvcCodeGenerator
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using SitecoreService.MvcCodeGenerator;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class ModelTemplate : ModelTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using E.SunBank.Foundation.SitecoreUtils.Extensions;\r\n      ");
            
            #line 8 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
    if(!string.IsNullOrEmpty(ChildClassName))
       { 
            
            #line default
            #line hidden
            this.Write("using E.SunBank.Project.eFingo.Models.");
            
            #line 10 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ChildClassName));
            
            #line default
            #line hidden
            this.Write(";\r\n      ");
            
            #line 11 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
 } 
    
            
            #line default
            #line hidden
            this.Write("using Sitecore.Data;\r\nusing Sitecore.Data.Items;\r\nusing System.Collections.Generi" +
                    "c;\r\nusing System.Linq;\r\n\r\nnamespace E.SunBank.Project.eFingo.Models.");
            
            #line 18 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    /// <summary>\r\n    /// ");
            
            #line 21 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DisplayName));
            
            #line default
            #line hidden
            this.Write("\r\n    /// </summary>\r\n    public class ");
            
            #line 23 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("Model\r\n    {\r\n        /// <summary>\r\n        /// DatasourceModel\r\n        /// </s" +
                    "ummary>\r\n        public ");
            
            #line 28 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("Item DatasourceItem { get; set; }\r\n        /// <summary>\r\n        /// 建構子\r\n      " +
                    "  /// </summary>\r\n        /// <param name=\"datasourceItem\"></param>\r\n        pub" +
                    "lic ");
            
            #line 33 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("Model(");
            
            #line 33 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("Item datasourceItem)\r\n        {\r\n            this.DatasourceItem = datasourceItem" +
                    ";\r\n        }\r\n    }\r\n\r\n    /// <summary>\r\n    /// ");
            
            #line 40 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DisplayName));
            
            #line default
            #line hidden
            this.Write("\r\n    /// </summary>\r\n    public class ");
            
            #line 42 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("Item\r\n    {\r\n        /// <summary>\r\n        /// ItemID\r\n        /// </summary>\r\n " +
                    "        public string Guid { get; set; }\r\n\r\n    ");
            
            #line 49 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
 foreach (Item item in Items)
       { 
            
            #line default
            #line hidden
            this.Write("    /// <summary>\r\n        /// ");
            
            #line 52 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.DisplayName));
            
            #line default
            #line hidden
            this.Write(" \r\n        /// </summary>\r\n        public string  ");
            
            #line 54 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ItemName));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n    ");
            
            #line 55 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
 } 
    
            
            #line default
            #line hidden
            this.Write("\r\n\r\n           ");
            
            #line 59 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
    if(!string.IsNullOrEmpty(ChildDisplayName))
       { 
            
            #line default
            #line hidden
            this.Write("        /// <summary>\r\n        /// ");
            
            #line 62 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ChildDisplayName));
            
            #line default
            #line hidden
            this.Write(" \r\n        /// </summary>\r\n        public IEnumerable<");
            
            #line 64 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ChildClassName));
            
            #line default
            #line hidden
            this.Write("Item> ");
            
            #line 64 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ChildClassName));
            
            #line default
            #line hidden
            this.Write("Items { get; set; }\r\n         ");
            
            #line 65 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
 } 
    
            
            #line default
            #line hidden
            this.Write("\r\n        /// <summary>\r\n        /// DatasourceItem本體\r\n        /// </summary>\r\n  " +
                    "      public Item DataItem { get; set; }\r\n        /// <summary>\r\n        /// 建構子" +
                    "1\r\n        /// </summary>\r\n        /// <param name=\"item\"></param>\r\n        publ" +
                    "ic ");
            
            #line 76 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("Item(Item item)\r\n        {\r\n            ");
            
            #line 78 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
 foreach (Item item in Items)
            {
            if(item.Type == "Image")
            {
            
            #line default
            #line hidden
            this.Write("              this.");
            
            #line 82 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ItemName));
            
            #line default
            #line hidden
            this.Write(" = item.ImageUrl(");
            
            #line 82 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("Template.FieldIDList.");
            
            #line 82 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ItemName));
            
            #line default
            #line hidden
            this.Write(");\r\n             ");
            
            #line 83 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
 }
                else if(item.Type == "Multi-Line Text")
             { 
            
            #line default
            #line hidden
            this.Write("              this.");
            
            #line 86 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ItemName));
            
            #line default
            #line hidden
            this.Write(" =  item.GetMultiLineText(");
            
            #line 86 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("Template.FieldIDList.");
            
            #line 86 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ItemName));
            
            #line default
            #line hidden
            this.Write(", \"<br>\").ToHtmlString();\r\n             ");
            
            #line 87 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
}
               else if(item.Type == "Droplink")
             { 
            
            #line default
            #line hidden
            this.Write("              Item linkItem = item?.TargetItem(");
            
            #line 90 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("Template.FieldIDList.");
            
            #line 90 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ItemName));
            
            #line default
            #line hidden
            this.Write(");\r\n                if (linkItem != null)\r\n                {\r\n                   " +
                    " //此處需修改ID\r\n                    this.");
            
            #line 94 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ItemName));
            
            #line default
            #line hidden
            this.Write("  = linkItem[");
            
            #line 94 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("Template.FieldIDList.");
            
            #line 94 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ItemName));
            
            #line default
            #line hidden
            this.Write("];\r\n                }\r\n             ");
            
            #line 96 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
} 
             else
             { 
            
            #line default
            #line hidden
            this.Write("              this.");
            
            #line 99 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ItemName));
            
            #line default
            #line hidden
            this.Write(" = item[");
            
            #line 99 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("Template.FieldIDList.");
            
            #line 99 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ItemName));
            
            #line default
            #line hidden
            this.Write("];\r\n             ");
            
            #line 100 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
} 
            }
            
            #line default
            #line hidden
            this.Write("\r\n\r\n                ");
            
            #line 104 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
    if(!string.IsNullOrEmpty(ChildClassName))
       { 
            
            #line default
            #line hidden
            this.Write("            this.");
            
            #line 106 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ChildClassName));
            
            #line default
            #line hidden
            this.Write("Items = item.GetChildren(");
            
            #line 106 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("Template.FieldIDList.");
            
            #line 106 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ChildClassName));
            
            #line default
            #line hidden
            this.Write("ID).Select(j => new ");
            
            #line 106 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ChildClassName));
            
            #line default
            #line hidden
            this.Write("Item(j)).ToList();\r\n             ");
            
            #line 107 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
 } 
    
            
            #line default
            #line hidden
            this.Write("\r\n            this.Guid = item.ID.ToString();\r\n            this.DataItem = item;\r" +
                    "\n        }\r\n    }\r\n\r\n    public class ");
            
            #line 115 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("Template\r\n    {\r\n        public class FieldIDList\r\n        {\r\n        ");
            
            #line 119 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
 foreach (Item item in Items)
            { 
            
            #line default
            #line hidden
            this.Write("    /// <summary>\r\n            /// ");
            
            #line 122 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.DisplayName));
            
            #line default
            #line hidden
            this.Write(" \r\n            /// </summary>\r\n            public static readonly ID ");
            
            #line 124 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ItemName));
            
            #line default
            #line hidden
            this.Write(" = new ID(\"{");
            
            #line 124 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ItemID));
            
            #line default
            #line hidden
            this.Write("}\");\r\n                           ");
            
            #line 125 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
    if(!string.IsNullOrEmpty(ChildClassName))
       { 
            
            #line default
            #line hidden
            this.Write("              /// <summary>\r\n            /// ");
            
            #line 128 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ChildDisplayName));
            
            #line default
            #line hidden
            this.Write(" \r\n            /// </summary>\r\n            public static readonly ID ");
            
            #line 130 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ChildClassName));
            
            #line default
            #line hidden
            this.Write("ID = new ID(\"{");
            
            #line 130 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ChildID));
            
            #line default
            #line hidden
            this.Write("}\");\r\n             ");
            
            #line 131 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
 } 
    
            
            #line default
            #line hidden
            this.Write("\\\r\n        ");
            
            #line 133 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"
 } 
        
            
            #line default
            #line hidden
            this.Write("        }\r\n    }\r\n}\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 145 "C:\Users\funan\source\repos\SitecoreService\SitecoreService\ModelTemplate.tt"

public List<Item> Items { get; set; }
public string ClassName { get; set; }
public string DisplayName { get; set; }
public string ChildClassName { get; set; }
public string ChildID { get; set; }
public string ChildDisplayName { get; set; }

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class ModelTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
